# Generated by Django 5.1.6 on 2025-03-11 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspace', '0005_remove_meshmodel_fbx_url_remove_meshmodel_glb_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('file_path', models.CharField(max_length=500)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='asset_thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeshAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('prompt', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('fbx_url', models.URLField(blank=True)),
                ('last_url_update', models.DateTimeField(null=True)),
                ('mesh_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workspace.meshmodel')),
            ],
            options={
                'ordering': ['-mesh_model__created_at'],
            },
        ),
    ]
