# Generated by Django 5.1.6 on 2025-03-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meshasset',
            name='has_texture',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meshasset',
            name='texture_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
