# Generated by Django 5.1.6 on 2025-03-10 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_rename_description_asset_content'),
        ('workspace', '0005_remove_meshmodel_fbx_url_remove_meshmodel_glb_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeshAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('fbx_url', models.URLField(blank=True)),
                ('last_url_update', models.DateTimeField(null=True)),
                ('mesh_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workspace.meshmodel')),
            ],
            options={
                'ordering': ['-mesh_model__created_at'],
            },
        ),
    ]
