# Generated by Django 5.1.6 on 2025-03-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_meshasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='meshasset',
            name='prompt',
            field=models.TextField(blank=True),
        ),
    ]
