# Generated by Django 5.1.6 on 2025-03-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meshmodel',
            name='create_prompt',
            field=models.TextField(default='2025-03-06 12:34:56'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meshmodel',
            name='fbx_path',
            field=models.FileField(blank=True, null=True, upload_to='meshes/fbx/'),
        ),
        migrations.AddField(
            model_name='meshmodel',
            name='fbx_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meshmodel',
            name='image_path',
            field=models.FileField(blank=True, null=True, upload_to='meshes/images/'),
        ),
        migrations.AddField(
            model_name='meshmodel',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meshmodel',
            name='video_path',
            field=models.FileField(blank=True, null=True, upload_to='meshes/videos/'),
        ),
        migrations.AddField(
            model_name='meshmodel',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
