# Generated by Django 5.1.6 on 2025-03-10 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0002_meshmodel_create_prompt_meshmodel_fbx_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meshmodel",
            name="glb_path",
            field=models.FileField(blank=True, null=True, upload_to="meshes/models/"),
        ),
        migrations.AddField(
            model_name="meshmodel",
            name="glb_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="meshmodel",
            name="metadata_path",
            field=models.FileField(blank=True, null=True, upload_to="meshes/"),
        ),
        migrations.AddField(
            model_name="meshmodel",
            name="metadata_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="meshmodel",
            name="obj_path",
            field=models.FileField(blank=True, null=True, upload_to="meshes/models/"),
        ),
        migrations.AddField(
            model_name="meshmodel",
            name="obj_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="meshmodel",
            name="usdz_path",
            field=models.FileField(blank=True, null=True, upload_to="meshes/models/"),
        ),
        migrations.AddField(
            model_name="meshmodel",
            name="usdz_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="meshmodel",
            name="fbx_path",
            field=models.FileField(blank=True, null=True, upload_to="meshes/models/"),
        ),
        migrations.AlterField(
            model_name="meshmodel",
            name="image_path",
            field=models.FileField(blank=True, null=True, upload_to="meshes/previews/"),
        ),
    ]
