# Generated by Django 5.1.6 on 2025-03-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0003_meshmodel_glb_path_meshmodel_glb_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meshmodel",
            name="fbx_path",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="meshmodel",
            name="glb_path",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="meshmodel",
            name="image_path",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="meshmodel",
            name="metadata_path",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="meshmodel",
            name="obj_path",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="meshmodel",
            name="usdz_path",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="meshmodel",
            name="video_path",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
