# Generated by Django 5.1.6 on 2025-03-10 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "workspace",
            "0004_alter_meshmodel_fbx_path_alter_meshmodel_glb_path_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meshmodel",
            name="fbx_url",
        ),
        migrations.RemoveField(
            model_name="meshmodel",
            name="glb_url",
        ),
        migrations.RemoveField(
            model_name="meshmodel",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="meshmodel",
            name="metadata_url",
        ),
        migrations.RemoveField(
            model_name="meshmodel",
            name="obj_url",
        ),
        migrations.RemoveField(
            model_name="meshmodel",
            name="usdz_url",
        ),
        migrations.RemoveField(
            model_name="meshmodel",
            name="video_url",
        ),
    ]
