# Generated by Django 5.1.6 on 2025-03-17 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "workspace",
            "0005_remove_meshmodel_fbx_url_remove_meshmodel_glb_url_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="meshmodel",
            name="base_color_path",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
