# Generated by Django 5.1.6 on 2025-03-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0006_meshmodel_base_color_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meshmodel",
            name="base_color_path",
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="meshmodel",
            name="fbx_path",
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="meshmodel",
            name="glb_path",
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="meshmodel",
            name="image_path",
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="meshmodel",
            name="metadata_path",
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="meshmodel",
            name="obj_path",
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="meshmodel",
            name="usdz_path",
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="meshmodel",
            name="video_path",
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=""),
        ),
    ]
