# Generated by Django 5.1.6 on 2025-03-12 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestMeshModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100, unique=True)),
                ('create_prompt', models.TextField(blank=True, null=True)),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('fbx_path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_mesh_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '테스트 메시 모델',
                'verbose_name_plural': '테스트 메시 모델 목록',
            },
        ),
        migrations.CreateModel(
            name='TestMeshAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('fbx_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mesh_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_asset', to='pgtest.testmeshmodel')),
            ],
            options={
                'verbose_name': '테스트 메시 에셋',
                'verbose_name_plural': '테스트 메시 에셋 목록',
            },
        ),
    ]
