# Generated by Django 5.1.6 on 2025-03-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like_type',
            field=models.CharField(choices=[('Like', 'like'), ('Dislike', 'dislike')], max_length=10),
        ),
    ]
