# Generated by Django 5.1.6 on 2025-03-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like_type',
            field=models.CharField(choices=[('❤️', 'like'), ('🤨', 'dislike')], max_length=10),
        ),
    ]
