# Generated by Django 5.1.6 on 2025-03-10 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_alter_like_like_type"),
        (
            "workspace",
            "0005_remove_meshmodel_fbx_url_remove_meshmodel_glb_url_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="job_id",
        ),
        migrations.AddField(
            model_name="article",
            name="create_prompt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="fbx_path",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="article",
            name="glb_path",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="article",
            name="image_path",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="article",
            name="job",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="article",
                to="workspace.meshmodel",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="metadata_path",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="article",
            name="obj_path",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="article",
            name="status",
            field=models.CharField(default="processing", max_length=50),
        ),
        migrations.AddField(
            model_name="article",
            name="usdz_path",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="article",
            name="video_path",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
