# Generated by Django 5.1.6 on 2025-03-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_remove_article_job_id_article_create_prompt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="base_color_path",
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="article",
            name="fbx_path",
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="article",
            name="glb_path",
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="article",
            name="image_path",
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="article",
            name="metadata_path",
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="article",
            name="obj_path",
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="article",
            name="usdz_path",
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="article",
            name="video_path",
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=""),
        ),
    ]
