# Generated by Django 5.1.6 on 2025-03-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_article_base_color_path_alter_article_fbx_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
