# Generated by Django 5.1.6 on 2025-03-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0006_alter_article_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="status",
            field=models.CharField(default="processing", max_length=255),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=512),
        ),
    ]
