# Generated by Django 5.1.6 on 2025-03-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0007_alter_article_status_alter_article_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(max_length=500, upload_to="article/image/"),
        ),
    ]
