# Generated by Django 5.1.6 on 2025-03-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("texture", "0002_remove_texturemodel_create_prompt_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="texturemodel",
            name="expires_at",
        ),
        migrations.RemoveField(
            model_name="texturemodel",
            name="finished_at",
        ),
        migrations.RemoveField(
            model_name="texturemodel",
            name="started_at",
        ),
        migrations.AlterField(
            model_name="texturemodel",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
