# Generated by Django 5.1.6 on 2025-03-21 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnhancedPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_prompt', models.TextField(help_text='사용자가 입력한 원본 프롬프트')),
                ('enhanced_prompts', models.TextField(help_text='LLM으로 개선된 프롬프트 목록 (JSON)')),
                ('selected_prompt', models.TextField(help_text='최종 선택된 개선 프롬프트')),
                ('selection_reason', models.TextField(blank=True, help_text='프롬프트 선택 이유')),
                ('scores', models.TextField(blank=True, help_text='프롬프트 평가 점수 (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_for_generation', models.BooleanField(default=False, help_text='3D 모델 생성에 사용되었는지 여부')),
                ('mesh_prompt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enhanced_versions', to='prompts.meshpromptmodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enhanced_prompts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '개선된 프롬프트',
                'verbose_name_plural': '개선된 프롬프트들',
                'ordering': ['-created_at'],
            },
        ),
    ]
